#!/usr/bin/env bash

# I do not use bash directly.
# So this file only includes `brew` binaries.

# global:
PATH="/usr/local/bin:$PATH"

# export PATH="$HOME/.poetry/bin:$PATH"

# export PATH="$HOME/.cargo/bin:$PATH"

. /usr/local/opt/asdf/libexec/asdf.sh

. /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash
